# Generated by Django 3.2 on 2022-01-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country'),
        ('checkout', '0002_auto_20220125_1535'),
    ]

    operations = [
    ]
